# Generated by Django 5.2.3 on 2025-06-17 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa grupy')),
                ('description', models.TextField(blank=True, verbose_name='Opis grupy')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Grupa plików',
                'verbose_name_plural': 'Grupy plików',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.CharField(max_length=500, unique=True, verbose_name='Ścieżka katalogu')),
                ('last_used_directory', models.CharField(blank=True, max_length=500, verbose_name='Ostatnio używany katalog')),
                ('code_patterns', models.JSONField(default=list, verbose_name='Wzorce kodu')),
                ('doc_patterns', models.JSONField(default=list, verbose_name='Wzorce dokumentacji')),
                ('concept_patterns', models.JSONField(default=list, verbose_name='Wzorce konceptów')),
                ('user_patterns', models.JSONField(default=list, verbose_name='Wzorce użytkownika')),
                ('global_include_patterns', models.JSONField(default=list, verbose_name='Globalne wzorce dołączania')),
                ('global_exclude_patterns', models.JSONField(default=list, verbose_name='Globalne wzorce wykluczania')),
                ('root_directory', models.CharField(blank=True, max_length=500, verbose_name='Katalog główny')),
                ('output_format', models.CharField(choices=[('md', 'Markdown'), ('xml', 'XML')], default='md', max_length=10, verbose_name='Format wyjścia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfiguracja Quick',
                'verbose_name_plural': 'Konfiguracje Quick',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=500, verbose_name='Wzorzec glob')),
                ('pattern_type', models.CharField(choices=[('include', 'Dołącz'), ('exclude', 'Wyklucz')], default='include', max_length=10, verbose_name='Typ wzorca')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('file_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='collector.filegroup')),
            ],
            options={
                'verbose_name': 'Wzorzec glob',
                'verbose_name_plural': 'Wzorce glob',
                'ordering': ['order', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa projektu')),
                ('description', models.TextField(blank=True, verbose_name='Opis projektu')),
                ('root_path', models.CharField(max_length=500, verbose_name='Ścieżka główna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_filename', models.CharField(default='output', max_length=200, verbose_name='Nazwa pliku wyjściowego')),
                ('output_style', models.CharField(choices=[('md', 'Markdown'), ('xml', 'XML')], default='md', max_length=10, verbose_name='Format wyjścia')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='filegroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_groups', to='collector.project'),
        ),
        migrations.CreateModel(
            name='CollectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file_path', models.CharField(max_length=500, verbose_name='Ścieżka pliku wyjściowego')),
                ('files_processed', models.PositiveIntegerField(default=0, verbose_name='Liczba przetworzonych plików')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Czas wykonania (s)')),
                ('success', models.BooleanField(default=True, verbose_name='Sukces')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat błędu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='collector.project')),
                ('quick_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='collector.quickconfig')),
            ],
            options={
                'verbose_name': 'Historia agregacji',
                'verbose_name_plural': 'Historia agregacji',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='Ścieżka')),
                ('recursive', models.BooleanField(default=True, verbose_name='Przeszukiwanie rekurencyjne')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('file_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_paths', to='collector.filegroup')),
            ],
            options={
                'verbose_name': 'Ścieżka przeszukiwania',
                'verbose_name_plural': 'Ścieżki przeszukiwania',
                'ordering': ['order', 'path'],
            },
        ),
    ]
