project_name: "Gatto PS AI Project"
output_file: ".doc-gen/comb-scripts-output.xml" # Re-enabled, changed to .xml
gitignore_file: ".gitignore"

repomix_global_options: # Added
  compress: false
  show_line_numbers: false
  calculate_tokens: false
  security_check: true
  style: "xml" # Default style

groups:
  - name: "Main Source Files"
    description: "Primary application source code"
    paths: ["app"]
    patterns: ["*.py"]
    exclude_patterns: ["*test*", "*__pycache__*"]
    repomix_options: # Example of group-specific override
      compress: true # Override global setting for this group

  - name: "Documentation"
    description: "Project documentation files"
    paths: ["docs", "."]
    patterns: ["*.md", "*.txt"]
    exclude_patterns: ["*temp*", "*backup*"]
