# =================================================================================
# KONFIGURACJA SKRYPTU AGREGACJI PLIKÓW
# Wersja: 5.1 (z grupami, konfiguracją YAML i exclude_patterns)
# =================================================================================

# Nazwa projektu
project_name: "Gatto Nero Ai Manager (PY+JSX+WebView no md)"

# Plik wyjściowy
output_file: ".doc-gen/.comb-project-max.md"

# Plik .gitignore do wykluczeń
gitignore_file: ".gitignore"

# =================================================================================
# GRUPY PLIKÓW
# =================================================================================
# Każda grupa ma:
# - name: nazwa grupy (wyświetlana w pliku wyjściowym)
# - description: opis grupy
# - patterns: wzorce plików do wyszukania
# - exclude_patterns: wzorce plików do wykluczenia (opcjonalne)
# - paths: ścieżki do przeszukania (względne do workspace_root)
# - recursive: czy szukać rekursywnie w podkatalogach

groups:
  - name: "Kod główny"
    description: "Pliki Markdown z dokumentacją algorytmów"
    patterns:
      - "*.py"
      - "*.json"
    exclude_patterns:
      - "*test*"
      - "*__pycache__*"
      - "*.pyc"
      - "*legacy*"
      - "*temp*"
    paths:
      - "**/*"
    recursive: true

  - name: "Webview"
    description: "Wszystkie pliki Python w workspace"
    patterns:
      - "*.py"
      - "*.html"
      - "*.css"
      - "*.js"
      - "*.json"
    exclude_patterns:
      - "*test*"
      - "*__pycache__*"
      - "*.pyc"
      - "*temp*"
    paths:
      - "app/webview"
    recursive: true
  - name: "Skrypty JSX"
    description: "Skrypty Adobe JSX dla Photoshop"
    patterns:
      - "*.jsx"
    exclude_patterns:
      - "*backup*"
      - "*old*"
    paths:
      - "app/scripts"
    recursive: true
